#!/usr/bin/env bash
# Bash script to install Nginx and configure it to serve "Holberton School"

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Create and configure the HTML file in /var/www/html
sudo mkdir -p /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure Nginx default server block
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Restart Nginx without systemctl
sudo service nginx restart


